version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    filters:
      branches:
        only:
          - Beauty

    steps:
      - checkout

      - run: cd ./web/client 

      - restore_cache:
          keys:
          # - node-v1-{{ .Branch }}-{{ .Revision }}
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}