version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    filters:
      branches:
        only:
          - Beauty

    steps:
      - checkout


      - run: cd ./web/client 

      - restore_cache:
          keys:
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}